# Generated by Django 5.1 on 2025-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_soildata_options_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
