# Generated by Django 5.1 on 2025-10-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_soildata_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('model_path', models.CharField(max_length=500)),
                ('dataset_size', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.JSONField()),
                ('feature_importance', models.JSONField()),
                ('training_metrics', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='api.modelversion')),
            ],
            options={
                'db_table': 'training_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
