# Generated by Django 5.1 on 2025-12-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_location_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='farm_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farm_size',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
