# Generated by Django 5.1 on 2025-07-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='crop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
