# Generated by Django 5.1 on 2025-08-09 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_soildata_crop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='', max_length=100)),
                ('nitrogen', models.FloatField(default=0.0)),
                ('phosphorus', models.FloatField(default=0.0)),
                ('potassium', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('ph', models.FloatField(default=7.0)),
                ('rainfall', models.FloatField(default=0.0)),
                ('predicted_yield', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='croprecommendation',
            options={'ordering': ['-recommendation_date']},
        ),
        migrations.AlterModelOptions(
            name='soildata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='systemfeedback',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.RemoveField(
            model_name='croprecommendation',
            name='crop_name',
        ),
        migrations.RemoveField(
            model_name='croprecommendation',
            name='suitability_score',
        ),
        migrations.RemoveField(
            model_name='sensordevice',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='sensordevice',
            name='sensor_name',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='systemfeedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='systemfeedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='recommended_crop',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='device_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='systemfeedback',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='systemfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('general', 'General Feedback')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='systemfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='systemfeedback',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='recommendation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='croprecommendation',
            name='soil_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_recommendations', to='dashboard.soildata'),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='date_installed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensordevice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='moisture',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='nitrogen',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='ph_level',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='phosphorus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='potassium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='rainfall',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_readings', to='dashboard.sensordevice'),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_soil_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemfeedback',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
